{
 "title": "course-app-logging",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "all-logs-course-app",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"course-app\"} |= \"\""
    }
   ]
  },
  {
   "title": "log-volume-course-app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=\"course-app\"}[5m])"
    }
   ]
  },
  {
   "title": "error-rate-course-app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=\"course-app\"} |= \"error\" [5m])"
    }
   ]
  },
  {
   "title": "top-error-message-course-app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, count_over_time({service_name=\"course-app\"} |= \"error\" [5m]))"
    }
   ]
  }
 ]
}