services:
  # DATABASE
  postgres:
    container_name: postgres
    image: postgres:16.4
    restart: on-failure
    environment:
      POSTGRES_USER: greenlight
      POSTGRES_PASSWORD: my-secret-pw
      POSTGRES_DB: greenlight
    ports:
      - '5432:5432'