// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package member_test

import (
	"context"

	"example.com/member/internal/member"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIService creates a new instance of MockIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIService {
	mock := &MockIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIService is an autogenerated mock type for the IService type
type MockIService struct {
	mock.Mock
}

type MockIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIService) EXPECT() *MockIService_Expecter {
	return &MockIService_Expecter{mock: &_m.Mock}
}

// DeleteByID provides a mock function for the type MockIService
func (_mock *MockIService) DeleteByID(ctx context.Context, memberID string) error {
	ret := _mock.Called(ctx, memberID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, memberID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIService_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockIService_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - memberID string
func (_e *MockIService_Expecter) DeleteByID(ctx interface{}, memberID interface{}) *MockIService_DeleteByID_Call {
	return &MockIService_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, memberID)}
}

func (_c *MockIService_DeleteByID_Call) Run(run func(ctx context.Context, memberID string)) *MockIService_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_DeleteByID_Call) Return(err error) *MockIService_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIService_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, memberID string) error) *MockIService_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockIService
func (_mock *MockIService) FindAll(ctx context.Context) ([]member.Member, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []member.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]member.Member, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []member.Member); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]member.Member)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockIService_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIService_Expecter) FindAll(ctx interface{}) *MockIService_FindAll_Call {
	return &MockIService_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockIService_FindAll_Call) Run(run func(ctx context.Context)) *MockIService_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIService_FindAll_Call) Return(members []member.Member, err error) *MockIService_FindAll_Call {
	_c.Call.Return(members, err)
	return _c
}

func (_c *MockIService_FindAll_Call) RunAndReturn(run func(ctx context.Context) ([]member.Member, error)) *MockIService_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCode provides a mock function for the type MockIService
func (_mock *MockIService) FindByCode(ctx context.Context, memberCode string) (*member.Member, error) {
	ret := _mock.Called(ctx, memberCode)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *member.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*member.Member, error)); ok {
		return returnFunc(ctx, memberCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *member.Member); ok {
		r0 = returnFunc(ctx, memberCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*member.Member)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, memberCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type MockIService_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - memberCode string
func (_e *MockIService_Expecter) FindByCode(ctx interface{}, memberCode interface{}) *MockIService_FindByCode_Call {
	return &MockIService_FindByCode_Call{Call: _e.mock.On("FindByCode", ctx, memberCode)}
}

func (_c *MockIService_FindByCode_Call) Run(run func(ctx context.Context, memberCode string)) *MockIService_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_FindByCode_Call) Return(member1 *member.Member, err error) *MockIService_FindByCode_Call {
	_c.Call.Return(member1, err)
	return _c
}

func (_c *MockIService_FindByCode_Call) RunAndReturn(run func(ctx context.Context, memberCode string) (*member.Member, error)) *MockIService_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockIService
func (_mock *MockIService) FindByEmail(ctx context.Context, memberEmail string) (*member.Member, error) {
	ret := _mock.Called(ctx, memberEmail)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *member.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*member.Member, error)); ok {
		return returnFunc(ctx, memberEmail)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *member.Member); ok {
		r0 = returnFunc(ctx, memberEmail)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*member.Member)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, memberEmail)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockIService_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - memberEmail string
func (_e *MockIService_Expecter) FindByEmail(ctx interface{}, memberEmail interface{}) *MockIService_FindByEmail_Call {
	return &MockIService_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, memberEmail)}
}

func (_c *MockIService_FindByEmail_Call) Run(run func(ctx context.Context, memberEmail string)) *MockIService_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_FindByEmail_Call) Return(member1 *member.Member, err error) *MockIService_FindByEmail_Call {
	_c.Call.Return(member1, err)
	return _c
}

func (_c *MockIService_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, memberEmail string) (*member.Member, error)) *MockIService_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockIService
func (_mock *MockIService) FindByID(ctx context.Context, memberID string) (*member.Member, error) {
	ret := _mock.Called(ctx, memberID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *member.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*member.Member, error)); ok {
		return returnFunc(ctx, memberID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *member.Member); ok {
		r0 = returnFunc(ctx, memberID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*member.Member)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, memberID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIService_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - memberID string
func (_e *MockIService_Expecter) FindByID(ctx interface{}, memberID interface{}) *MockIService_FindByID_Call {
	return &MockIService_FindByID_Call{Call: _e.mock.On("FindByID", ctx, memberID)}
}

func (_c *MockIService_FindByID_Call) Run(run func(ctx context.Context, memberID string)) *MockIService_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_FindByID_Call) Return(member1 *member.Member, err error) *MockIService_FindByID_Call {
	_c.Call.Return(member1, err)
	return _c
}

func (_c *MockIService_FindByID_Call) RunAndReturn(run func(ctx context.Context, memberID string) (*member.Member, error)) *MockIService_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockIService
func (_mock *MockIService) Save(ctx context.Context, member1 *member.Member) (*member.Member, error) {
	ret := _mock.Called(ctx, member1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *member.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *member.Member) (*member.Member, error)); ok {
		return returnFunc(ctx, member1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *member.Member) *member.Member); ok {
		r0 = returnFunc(ctx, member1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*member.Member)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *member.Member) error); ok {
		r1 = returnFunc(ctx, member1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockIService_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - member1 *member.Member
func (_e *MockIService_Expecter) Save(ctx interface{}, member1 interface{}) *MockIService_Save_Call {
	return &MockIService_Save_Call{Call: _e.mock.On("Save", ctx, member1)}
}

func (_c *MockIService_Save_Call) Run(run func(ctx context.Context, member1 *member.Member)) *MockIService_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *member.Member
		if args[1] != nil {
			arg1 = args[1].(*member.Member)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_Save_Call) Return(member11 *member.Member, err error) *MockIService_Save_Call {
	_c.Call.Return(member11, err)
	return _c
}

func (_c *MockIService_Save_Call) RunAndReturn(run func(ctx context.Context, member1 *member.Member) (*member.Member, error)) *MockIService_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIStore creates a new instance of MockIStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStore {
	mock := &MockIStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIStore is an autogenerated mock type for the IStore type
type MockIStore struct {
	mock.Mock
}

type MockIStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStore) EXPECT() *MockIStore_Expecter {
	return &MockIStore_Expecter{mock: &_m.Mock}
}

// DeleteByID provides a mock function for the type MockIStore
func (_mock *MockIStore) DeleteByID(ctx context.Context, memberID string) error {
	ret := _mock.Called(ctx, memberID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, memberID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIStore_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockIStore_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - memberID string
func (_e *MockIStore_Expecter) DeleteByID(ctx interface{}, memberID interface{}) *MockIStore_DeleteByID_Call {
	return &MockIStore_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, memberID)}
}

func (_c *MockIStore_DeleteByID_Call) Run(run func(ctx context.Context, memberID string)) *MockIStore_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStore_DeleteByID_Call) Return(err error) *MockIStore_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIStore_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, memberID string) error) *MockIStore_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockIStore
func (_mock *MockIStore) FindAll(ctx context.Context) ([]member.Member, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []member.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]member.Member, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []member.Member); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]member.Member)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStore_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockIStore_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIStore_Expecter) FindAll(ctx interface{}) *MockIStore_FindAll_Call {
	return &MockIStore_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockIStore_FindAll_Call) Run(run func(ctx context.Context)) *MockIStore_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIStore_FindAll_Call) Return(members []member.Member, err error) *MockIStore_FindAll_Call {
	_c.Call.Return(members, err)
	return _c
}

func (_c *MockIStore_FindAll_Call) RunAndReturn(run func(ctx context.Context) ([]member.Member, error)) *MockIStore_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCode provides a mock function for the type MockIStore
func (_mock *MockIStore) FindByCode(ctx context.Context, memberCode string) (*member.Member, error) {
	ret := _mock.Called(ctx, memberCode)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *member.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*member.Member, error)); ok {
		return returnFunc(ctx, memberCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *member.Member); ok {
		r0 = returnFunc(ctx, memberCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*member.Member)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, memberCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStore_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type MockIStore_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - memberCode string
func (_e *MockIStore_Expecter) FindByCode(ctx interface{}, memberCode interface{}) *MockIStore_FindByCode_Call {
	return &MockIStore_FindByCode_Call{Call: _e.mock.On("FindByCode", ctx, memberCode)}
}

func (_c *MockIStore_FindByCode_Call) Run(run func(ctx context.Context, memberCode string)) *MockIStore_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStore_FindByCode_Call) Return(member1 *member.Member, err error) *MockIStore_FindByCode_Call {
	_c.Call.Return(member1, err)
	return _c
}

func (_c *MockIStore_FindByCode_Call) RunAndReturn(run func(ctx context.Context, memberCode string) (*member.Member, error)) *MockIStore_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockIStore
func (_mock *MockIStore) FindByEmail(ctx context.Context, memberEmail string) (*member.Member, error) {
	ret := _mock.Called(ctx, memberEmail)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *member.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*member.Member, error)); ok {
		return returnFunc(ctx, memberEmail)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *member.Member); ok {
		r0 = returnFunc(ctx, memberEmail)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*member.Member)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, memberEmail)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStore_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockIStore_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - memberEmail string
func (_e *MockIStore_Expecter) FindByEmail(ctx interface{}, memberEmail interface{}) *MockIStore_FindByEmail_Call {
	return &MockIStore_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, memberEmail)}
}

func (_c *MockIStore_FindByEmail_Call) Run(run func(ctx context.Context, memberEmail string)) *MockIStore_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStore_FindByEmail_Call) Return(member1 *member.Member, err error) *MockIStore_FindByEmail_Call {
	_c.Call.Return(member1, err)
	return _c
}

func (_c *MockIStore_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, memberEmail string) (*member.Member, error)) *MockIStore_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockIStore
func (_mock *MockIStore) FindByID(ctx context.Context, memberID string) (*member.Member, error) {
	ret := _mock.Called(ctx, memberID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *member.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*member.Member, error)); ok {
		return returnFunc(ctx, memberID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *member.Member); ok {
		r0 = returnFunc(ctx, memberID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*member.Member)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, memberID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStore_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIStore_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - memberID string
func (_e *MockIStore_Expecter) FindByID(ctx interface{}, memberID interface{}) *MockIStore_FindByID_Call {
	return &MockIStore_FindByID_Call{Call: _e.mock.On("FindByID", ctx, memberID)}
}

func (_c *MockIStore_FindByID_Call) Run(run func(ctx context.Context, memberID string)) *MockIStore_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStore_FindByID_Call) Return(member1 *member.Member, err error) *MockIStore_FindByID_Call {
	_c.Call.Return(member1, err)
	return _c
}

func (_c *MockIStore_FindByID_Call) RunAndReturn(run func(ctx context.Context, memberID string) (*member.Member, error)) *MockIStore_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockIStore
func (_mock *MockIStore) Save(ctx context.Context, member1 *member.Member) error {
	ret := _mock.Called(ctx, member1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *member.Member) error); ok {
		r0 = returnFunc(ctx, member1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockIStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - member1 *member.Member
func (_e *MockIStore_Expecter) Save(ctx interface{}, member1 interface{}) *MockIStore_Save_Call {
	return &MockIStore_Save_Call{Call: _e.mock.On("Save", ctx, member1)}
}

func (_c *MockIStore_Save_Call) Run(run func(ctx context.Context, member1 *member.Member)) *MockIStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *member.Member
		if args[1] != nil {
			arg1 = args[1].(*member.Member)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStore_Save_Call) Return(err error) *MockIStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIStore_Save_Call) RunAndReturn(run func(ctx context.Context, member1 *member.Member) error) *MockIStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
