{
 "title": "member-app-metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "cpu-usage-member-app",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(system_cpu_usage_percent{job=\"member-app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory-usage-member-app",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(system_memory_usage_bytes{job=\"member-app\"}/system_memory_total_bytes{job=\"member-app\"})*100"
    }
   ]
  },
  {
   "title": "disk-usage-member-app",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(system_disk_usage_bytes{job=\"member-app\"}/system_disk_total_bytes{job=\"member-app\"})*100"
    }
   ]
  }
 ]
}