grpc:
  host: "0.0.0.0"
  port: "50051"

http:
  host: "0.0.0.0"
  port: "8080"

log:
  level: "debug"                # Options: debug, info, warn, error
  type: "console"               # Options: console, json, etc.
  logFileEnabled: false
  logFilePath: "logs/app.log"

db:
  host: "localhost"
  port: "5432"
  name: "devdb"
  user: "dev"
  password: "P4ssword!"
  maxIdleConn: 10
  maxOpenConn: 50

redis:
  host: "localhost"
  port: "6379"
  db: 0
  password: ""
  connDialTimeoutSec: 5     # Connection dial timeout (seconds)
  readTimeoutSec: 3         # Socket read timeout (0=default, -1=none, -2=disable deadline)
  writeTimeoutSec: 3        # Socket write timeout (same as above)
  connPoolSize: 20          # Max total connections
  connPoolTimeoutSec: 4     # Wait time for connection (seconds)
  minIdleConn: 5            # Minimum idle connections
  maxIdleConn: 10           # Maximum idle connections