// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package booking_test

import (
	"context"

	"example.com/booking/internal/booking"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIClient creates a new instance of MockIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIClient {
	mock := &MockIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIClient is an autogenerated mock type for the IClient type
type MockIClient struct {
	mock.Mock
}

type MockIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIClient) EXPECT() *MockIClient_Expecter {
	return &MockIClient_Expecter{mock: &_m.Mock}
}

// FindMemberByCode provides a mock function for the type MockIClient
func (_mock *MockIClient) FindMemberByCode(ctx context.Context, memberCode string) (*booking.MemberServiceMemberResponse, error) {
	ret := _mock.Called(ctx, memberCode)

	if len(ret) == 0 {
		panic("no return value specified for FindMemberByCode")
	}

	var r0 *booking.MemberServiceMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*booking.MemberServiceMemberResponse, error)); ok {
		return returnFunc(ctx, memberCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *booking.MemberServiceMemberResponse); ok {
		r0 = returnFunc(ctx, memberCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*booking.MemberServiceMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, memberCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIClient_FindMemberByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMemberByCode'
type MockIClient_FindMemberByCode_Call struct {
	*mock.Call
}

// FindMemberByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - memberCode string
func (_e *MockIClient_Expecter) FindMemberByCode(ctx interface{}, memberCode interface{}) *MockIClient_FindMemberByCode_Call {
	return &MockIClient_FindMemberByCode_Call{Call: _e.mock.On("FindMemberByCode", ctx, memberCode)}
}

func (_c *MockIClient_FindMemberByCode_Call) Run(run func(ctx context.Context, memberCode string)) *MockIClient_FindMemberByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIClient_FindMemberByCode_Call) Return(memberServiceMemberResponse *booking.MemberServiceMemberResponse, err error) *MockIClient_FindMemberByCode_Call {
	_c.Call.Return(memberServiceMemberResponse, err)
	return _c
}

func (_c *MockIClient_FindMemberByCode_Call) RunAndReturn(run func(ctx context.Context, memberCode string) (*booking.MemberServiceMemberResponse, error)) *MockIClient_FindMemberByCode_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseCourseByCode provides a mock function for the type MockIClient
func (_mock *MockIClient) ReleaseCourseByCode(ctx context.Context, courseCode string) (*booking.CourseServiceMessageResponse, error) {
	ret := _mock.Called(ctx, courseCode)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseCourseByCode")
	}

	var r0 *booking.CourseServiceMessageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*booking.CourseServiceMessageResponse, error)); ok {
		return returnFunc(ctx, courseCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *booking.CourseServiceMessageResponse); ok {
		r0 = returnFunc(ctx, courseCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*booking.CourseServiceMessageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, courseCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIClient_ReleaseCourseByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseCourseByCode'
type MockIClient_ReleaseCourseByCode_Call struct {
	*mock.Call
}

// ReleaseCourseByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - courseCode string
func (_e *MockIClient_Expecter) ReleaseCourseByCode(ctx interface{}, courseCode interface{}) *MockIClient_ReleaseCourseByCode_Call {
	return &MockIClient_ReleaseCourseByCode_Call{Call: _e.mock.On("ReleaseCourseByCode", ctx, courseCode)}
}

func (_c *MockIClient_ReleaseCourseByCode_Call) Run(run func(ctx context.Context, courseCode string)) *MockIClient_ReleaseCourseByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIClient_ReleaseCourseByCode_Call) Return(courseServiceMessageResponse *booking.CourseServiceMessageResponse, err error) *MockIClient_ReleaseCourseByCode_Call {
	_c.Call.Return(courseServiceMessageResponse, err)
	return _c
}

func (_c *MockIClient_ReleaseCourseByCode_Call) RunAndReturn(run func(ctx context.Context, courseCode string) (*booking.CourseServiceMessageResponse, error)) *MockIClient_ReleaseCourseByCode_Call {
	_c.Call.Return(run)
	return _c
}

// ReserveCourseByCode provides a mock function for the type MockIClient
func (_mock *MockIClient) ReserveCourseByCode(ctx context.Context, courseCode string) (*booking.CourseServiceMessageResponse, error) {
	ret := _mock.Called(ctx, courseCode)

	if len(ret) == 0 {
		panic("no return value specified for ReserveCourseByCode")
	}

	var r0 *booking.CourseServiceMessageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*booking.CourseServiceMessageResponse, error)); ok {
		return returnFunc(ctx, courseCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *booking.CourseServiceMessageResponse); ok {
		r0 = returnFunc(ctx, courseCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*booking.CourseServiceMessageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, courseCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIClient_ReserveCourseByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReserveCourseByCode'
type MockIClient_ReserveCourseByCode_Call struct {
	*mock.Call
}

// ReserveCourseByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - courseCode string
func (_e *MockIClient_Expecter) ReserveCourseByCode(ctx interface{}, courseCode interface{}) *MockIClient_ReserveCourseByCode_Call {
	return &MockIClient_ReserveCourseByCode_Call{Call: _e.mock.On("ReserveCourseByCode", ctx, courseCode)}
}

func (_c *MockIClient_ReserveCourseByCode_Call) Run(run func(ctx context.Context, courseCode string)) *MockIClient_ReserveCourseByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIClient_ReserveCourseByCode_Call) Return(courseServiceMessageResponse *booking.CourseServiceMessageResponse, err error) *MockIClient_ReserveCourseByCode_Call {
	_c.Call.Return(courseServiceMessageResponse, err)
	return _c
}

func (_c *MockIClient_ReserveCourseByCode_Call) RunAndReturn(run func(ctx context.Context, courseCode string) (*booking.CourseServiceMessageResponse, error)) *MockIClient_ReserveCourseByCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIService creates a new instance of MockIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIService {
	mock := &MockIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIService is an autogenerated mock type for the IService type
type MockIService struct {
	mock.Mock
}

type MockIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIService) EXPECT() *MockIService_Expecter {
	return &MockIService_Expecter{mock: &_m.Mock}
}

// Booking provides a mock function for the type MockIService
func (_mock *MockIService) Booking(ctx context.Context, request booking.BookingRequest) (*booking.Booking, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Booking")
	}

	var r0 *booking.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, booking.BookingRequest) (*booking.Booking, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, booking.BookingRequest) *booking.Booking); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*booking.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, booking.BookingRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_Booking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Booking'
type MockIService_Booking_Call struct {
	*mock.Call
}

// Booking is a helper method to define mock.On call
//   - ctx context.Context
//   - request booking.BookingRequest
func (_e *MockIService_Expecter) Booking(ctx interface{}, request interface{}) *MockIService_Booking_Call {
	return &MockIService_Booking_Call{Call: _e.mock.On("Booking", ctx, request)}
}

func (_c *MockIService_Booking_Call) Run(run func(ctx context.Context, request booking.BookingRequest)) *MockIService_Booking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 booking.BookingRequest
		if args[1] != nil {
			arg1 = args[1].(booking.BookingRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_Booking_Call) Return(booking1 *booking.Booking, err error) *MockIService_Booking_Call {
	_c.Call.Return(booking1, err)
	return _c
}

func (_c *MockIService_Booking_Call) RunAndReturn(run func(ctx context.Context, request booking.BookingRequest) (*booking.Booking, error)) *MockIService_Booking_Call {
	_c.Call.Return(run)
	return _c
}

// BookingV2 provides a mock function for the type MockIService
func (_mock *MockIService) BookingV2(ctx context.Context, request booking.BookingRequest) (*booking.Booking, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for BookingV2")
	}

	var r0 *booking.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, booking.BookingRequest) (*booking.Booking, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, booking.BookingRequest) *booking.Booking); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*booking.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, booking.BookingRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_BookingV2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BookingV2'
type MockIService_BookingV2_Call struct {
	*mock.Call
}

// BookingV2 is a helper method to define mock.On call
//   - ctx context.Context
//   - request booking.BookingRequest
func (_e *MockIService_Expecter) BookingV2(ctx interface{}, request interface{}) *MockIService_BookingV2_Call {
	return &MockIService_BookingV2_Call{Call: _e.mock.On("BookingV2", ctx, request)}
}

func (_c *MockIService_BookingV2_Call) Run(run func(ctx context.Context, request booking.BookingRequest)) *MockIService_BookingV2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 booking.BookingRequest
		if args[1] != nil {
			arg1 = args[1].(booking.BookingRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_BookingV2_Call) Return(booking1 *booking.Booking, err error) *MockIService_BookingV2_Call {
	_c.Call.Return(booking1, err)
	return _c
}

func (_c *MockIService_BookingV2_Call) RunAndReturn(run func(ctx context.Context, request booking.BookingRequest) (*booking.Booking, error)) *MockIService_BookingV2_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIStore creates a new instance of MockIStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStore {
	mock := &MockIStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIStore is an autogenerated mock type for the IStore type
type MockIStore struct {
	mock.Mock
}

type MockIStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStore) EXPECT() *MockIStore_Expecter {
	return &MockIStore_Expecter{mock: &_m.Mock}
}

// DeleteByID provides a mock function for the type MockIStore
func (_mock *MockIStore) DeleteByID(ctx context.Context, bookingID string) error {
	ret := _mock.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, bookingID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIStore_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockIStore_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID string
func (_e *MockIStore_Expecter) DeleteByID(ctx interface{}, bookingID interface{}) *MockIStore_DeleteByID_Call {
	return &MockIStore_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, bookingID)}
}

func (_c *MockIStore_DeleteByID_Call) Run(run func(ctx context.Context, bookingID string)) *MockIStore_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStore_DeleteByID_Call) Return(err error) *MockIStore_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIStore_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, bookingID string) error) *MockIStore_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockIStore
func (_mock *MockIStore) FindAll(ctx context.Context) ([]booking.Booking, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []booking.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]booking.Booking, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []booking.Booking); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]booking.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStore_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockIStore_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIStore_Expecter) FindAll(ctx interface{}) *MockIStore_FindAll_Call {
	return &MockIStore_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockIStore_FindAll_Call) Run(run func(ctx context.Context)) *MockIStore_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIStore_FindAll_Call) Return(bookings []booking.Booking, err error) *MockIStore_FindAll_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockIStore_FindAll_Call) RunAndReturn(run func(ctx context.Context) ([]booking.Booking, error)) *MockIStore_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByCourseCode provides a mock function for the type MockIStore
func (_mock *MockIStore) FindAllByCourseCode(ctx context.Context, courseCode string) ([]booking.Booking, error) {
	ret := _mock.Called(ctx, courseCode)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByCourseCode")
	}

	var r0 []booking.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]booking.Booking, error)); ok {
		return returnFunc(ctx, courseCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []booking.Booking); ok {
		r0 = returnFunc(ctx, courseCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]booking.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, courseCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStore_FindAllByCourseCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByCourseCode'
type MockIStore_FindAllByCourseCode_Call struct {
	*mock.Call
}

// FindAllByCourseCode is a helper method to define mock.On call
//   - ctx context.Context
//   - courseCode string
func (_e *MockIStore_Expecter) FindAllByCourseCode(ctx interface{}, courseCode interface{}) *MockIStore_FindAllByCourseCode_Call {
	return &MockIStore_FindAllByCourseCode_Call{Call: _e.mock.On("FindAllByCourseCode", ctx, courseCode)}
}

func (_c *MockIStore_FindAllByCourseCode_Call) Run(run func(ctx context.Context, courseCode string)) *MockIStore_FindAllByCourseCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStore_FindAllByCourseCode_Call) Return(bookings []booking.Booking, err error) *MockIStore_FindAllByCourseCode_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockIStore_FindAllByCourseCode_Call) RunAndReturn(run func(ctx context.Context, courseCode string) ([]booking.Booking, error)) *MockIStore_FindAllByCourseCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByMemberCode provides a mock function for the type MockIStore
func (_mock *MockIStore) FindAllByMemberCode(ctx context.Context, memberCode string) ([]booking.Booking, error) {
	ret := _mock.Called(ctx, memberCode)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByMemberCode")
	}

	var r0 []booking.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]booking.Booking, error)); ok {
		return returnFunc(ctx, memberCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []booking.Booking); ok {
		r0 = returnFunc(ctx, memberCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]booking.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, memberCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStore_FindAllByMemberCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByMemberCode'
type MockIStore_FindAllByMemberCode_Call struct {
	*mock.Call
}

// FindAllByMemberCode is a helper method to define mock.On call
//   - ctx context.Context
//   - memberCode string
func (_e *MockIStore_Expecter) FindAllByMemberCode(ctx interface{}, memberCode interface{}) *MockIStore_FindAllByMemberCode_Call {
	return &MockIStore_FindAllByMemberCode_Call{Call: _e.mock.On("FindAllByMemberCode", ctx, memberCode)}
}

func (_c *MockIStore_FindAllByMemberCode_Call) Run(run func(ctx context.Context, memberCode string)) *MockIStore_FindAllByMemberCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStore_FindAllByMemberCode_Call) Return(bookings []booking.Booking, err error) *MockIStore_FindAllByMemberCode_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockIStore_FindAllByMemberCode_Call) RunAndReturn(run func(ctx context.Context, memberCode string) ([]booking.Booking, error)) *MockIStore_FindAllByMemberCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByStatus provides a mock function for the type MockIStore
func (_mock *MockIStore) FindAllByStatus(ctx context.Context, status booking.BookingStatus) ([]booking.Booking, error) {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByStatus")
	}

	var r0 []booking.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, booking.BookingStatus) ([]booking.Booking, error)); ok {
		return returnFunc(ctx, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, booking.BookingStatus) []booking.Booking); ok {
		r0 = returnFunc(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]booking.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, booking.BookingStatus) error); ok {
		r1 = returnFunc(ctx, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStore_FindAllByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByStatus'
type MockIStore_FindAllByStatus_Call struct {
	*mock.Call
}

// FindAllByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status booking.BookingStatus
func (_e *MockIStore_Expecter) FindAllByStatus(ctx interface{}, status interface{}) *MockIStore_FindAllByStatus_Call {
	return &MockIStore_FindAllByStatus_Call{Call: _e.mock.On("FindAllByStatus", ctx, status)}
}

func (_c *MockIStore_FindAllByStatus_Call) Run(run func(ctx context.Context, status booking.BookingStatus)) *MockIStore_FindAllByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 booking.BookingStatus
		if args[1] != nil {
			arg1 = args[1].(booking.BookingStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStore_FindAllByStatus_Call) Return(bookings []booking.Booking, err error) *MockIStore_FindAllByStatus_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockIStore_FindAllByStatus_Call) RunAndReturn(run func(ctx context.Context, status booking.BookingStatus) ([]booking.Booking, error)) *MockIStore_FindAllByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockIStore
func (_mock *MockIStore) FindByID(ctx context.Context, bookingID string) (*booking.Booking, error) {
	ret := _mock.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *booking.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*booking.Booking, error)); ok {
		return returnFunc(ctx, bookingID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *booking.Booking); ok {
		r0 = returnFunc(ctx, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*booking.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStore_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIStore_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID string
func (_e *MockIStore_Expecter) FindByID(ctx interface{}, bookingID interface{}) *MockIStore_FindByID_Call {
	return &MockIStore_FindByID_Call{Call: _e.mock.On("FindByID", ctx, bookingID)}
}

func (_c *MockIStore_FindByID_Call) Run(run func(ctx context.Context, bookingID string)) *MockIStore_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStore_FindByID_Call) Return(booking1 *booking.Booking, err error) *MockIStore_FindByID_Call {
	_c.Call.Return(booking1, err)
	return _c
}

func (_c *MockIStore_FindByID_Call) RunAndReturn(run func(ctx context.Context, bookingID string) (*booking.Booking, error)) *MockIStore_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockIStore
func (_mock *MockIStore) Save(ctx context.Context, booking1 *booking.Booking) error {
	ret := _mock.Called(ctx, booking1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *booking.Booking) error); ok {
		r0 = returnFunc(ctx, booking1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockIStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - booking1 *booking.Booking
func (_e *MockIStore_Expecter) Save(ctx interface{}, booking1 interface{}) *MockIStore_Save_Call {
	return &MockIStore_Save_Call{Call: _e.mock.On("Save", ctx, booking1)}
}

func (_c *MockIStore_Save_Call) Run(run func(ctx context.Context, booking1 *booking.Booking)) *MockIStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *booking.Booking
		if args[1] != nil {
			arg1 = args[1].(*booking.Booking)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStore_Save_Call) Return(err error) *MockIStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIStore_Save_Call) RunAndReturn(run func(ctx context.Context, booking1 *booking.Booking) error) *MockIStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
