services:
  mysql:
    image: mysql:9.3
    container_name: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox
      MYSQL_USER: sandboxuser
      MYSQL_PASSWORD: sandboxpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sandbox_net
  
volumes:
  mysql_data:

networks:
  sandbox_net:
    driver: bridge