services:
  graylog:
    image: graylog/graylog:6.1
    container_name: graylog
    restart: on-failure
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      # To make reporting (headless_shell) work inside a Docker container
      GRAYLOG_REPORT_DISABLE_SANDBOX: "true"
      # CHANGE ME (must be at least 16 characters)!
      GRAYLOG_PASSWORD_SECRET: "somepasswordpepper"
      # Password: "admin"
      GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
    entrypoint: >
      /usr/bin/tini -- 
      wait-for-it opensearch:9200 -- 
      /docker-entrypoint.sh
    ports:
      - "9000:9000"       # Graylog web interface and REST API
      - "5044:5044/tcp"   # Beats
      - "5140:5140"       # Syslog TCP
      - "5140:5140/udp"   # Syslog UDP
      - "12201:12201"     # GELF TCP
      - "12201:12201/udp" # GELF UDP
      - "13301:13301/tcp" # Forwarder data
      - "13302:13302/tcp" # Forwarder config
    volumes:
      - graylog_data:/usr/share/graylog/data
    networks:
      - dev
    depends_on:
      mongodb: 
        condition: "service_started" 
      opensearch:
        condition: "service_started"

  mongodb:
    image: mongo:6.0.18
    container_name: mongo
    restart: on-failure
    volumes:
      - mongo_db:/data/db
      - mongo_config:/data/configdb
    networks:
      - dev

  opensearch:
    image: opensearchproject/opensearch:2.15.0
    container_name: opensearch
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g"
      bootstrap.memory_lock: true
      discovery.type: single-node
      action.auto_create_index: false
      plugins.security.ssl.http.enabled: false
      plugins.security.disabled: true
      # Can generate a password for `OPENSEARCH_INITIAL_ADMIN_PASSWORD` using a linux device via:
      # tr -dc A-Z-a-z-0-9_@#%^-_=+ < /dev/urandom | head -c${1:-32}
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: +_8r#wliY3Pv5-HMIf4qzXImYzZf-M=M
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9203:9200"
      - "9303:9300" 
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - dev

volumes:
  graylog_data:
  graylog_journal:
  mongo_db:
  mongo_config:
  opensearch_data:

networks:
  dev:
    driver: bridge