services:
  graylog:
    image: graylog/graylog:5.0
    container_name: graylog
    restart: on-failure
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_HTTP_EXTERNAL_URI: http://127.0.0.1:9000/
    entrypoint: >
      /usr/bin/tini -- 
      wait-for-it elasticsearch:9200 -- 
      /docker-entrypoint.sh
    ports:
      - "9000:9000"       # Graylog web interface and REST API
      - "1514:1514"       # Syslog TCP
      - "1514:1514/udp"   # Syslog UDP
      - "12201:12201"     # GELF TCP
      - "12201:12201/udp" # GELF UDP
    volumes:
      - graylog_data:/usr/share/graylog/data
      - graylog_journal:/usr/share/graylog/data/journal
    networks:
      - dev
    depends_on:
      - mongo
      - elasticsearch

  mongo:
    image: mongo:5.0.13
    container_name: mongo
    restart: on-failure
    volumes:
      - mongo_db:/data/db
    networks:
      - dev

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: elasticsearch
    environment:
      http.host: 0.0.0.0
      transport.host: localhost
      network.host: 0.0.0.0
      ES_JAVA_OPTS: "-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - dev

volumes:
  graylog_data:
  graylog_journal:
  mongo_db:
  elasticsearch_data:

networks:
  dev:
    driver: bridge