services:
  redis:
    image: redis:7
    container_name: redis
    restart: on-failure
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    networks:
      - flightnet

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5000:5540"
    networks:
      - flightnet
    depends_on:
      - redis

networks:
  flightnet:
    driver: bridge