template: testify
packages:
    example.com/course/internal/course:
        config:
            dir: "{{.InterfaceDir}}"
            filename: "mock_test.go"
            pkgname: "course_test"
            structname: "Mock{{.InterfaceName}}"
        interfaces:
            IStore:
            IService: