services:
  postgres:
    image: postgres:17.6
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sandboxpass
      POSTGRES_DB: sandbox
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - sandbox_net

volumes:
  pg_data:

networks:
  sandbox_net:
    driver: bridge
    