services:
  pgadmin:
    image: dpage/pgadmin4:9.11
    container_name: pgadmin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sandbox.com
      PGADMIN_DEFAULT_PASSWORD: sandboxpass
    ports:
      - "80:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
