// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package course_test

import (
	"context"

	"example.com/course/internal/course"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIService creates a new instance of MockIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIService {
	mock := &MockIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIService is an autogenerated mock type for the IService type
type MockIService struct {
	mock.Mock
}

type MockIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIService) EXPECT() *MockIService_Expecter {
	return &MockIService_Expecter{mock: &_m.Mock}
}

// DeleteByID provides a mock function for the type MockIService
func (_mock *MockIService) DeleteByID(ctx context.Context, courseID string) error {
	ret := _mock.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, courseID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIService_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockIService_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
func (_e *MockIService_Expecter) DeleteByID(ctx interface{}, courseID interface{}) *MockIService_DeleteByID_Call {
	return &MockIService_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, courseID)}
}

func (_c *MockIService_DeleteByID_Call) Run(run func(ctx context.Context, courseID string)) *MockIService_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_DeleteByID_Call) Return(err error) *MockIService_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIService_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, courseID string) error) *MockIService_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockIService
func (_mock *MockIService) FindAll(ctx context.Context) ([]course.Course, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []course.Course
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]course.Course, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []course.Course); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]course.Course)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockIService_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIService_Expecter) FindAll(ctx interface{}) *MockIService_FindAll_Call {
	return &MockIService_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockIService_FindAll_Call) Run(run func(ctx context.Context)) *MockIService_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIService_FindAll_Call) Return(courses []course.Course, err error) *MockIService_FindAll_Call {
	_c.Call.Return(courses, err)
	return _c
}

func (_c *MockIService_FindAll_Call) RunAndReturn(run func(ctx context.Context) ([]course.Course, error)) *MockIService_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCode provides a mock function for the type MockIService
func (_mock *MockIService) FindByCode(ctx context.Context, courseCode string) (*course.Course, error) {
	ret := _mock.Called(ctx, courseCode)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *course.Course
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*course.Course, error)); ok {
		return returnFunc(ctx, courseCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *course.Course); ok {
		r0 = returnFunc(ctx, courseCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*course.Course)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, courseCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type MockIService_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - courseCode string
func (_e *MockIService_Expecter) FindByCode(ctx interface{}, courseCode interface{}) *MockIService_FindByCode_Call {
	return &MockIService_FindByCode_Call{Call: _e.mock.On("FindByCode", ctx, courseCode)}
}

func (_c *MockIService_FindByCode_Call) Run(run func(ctx context.Context, courseCode string)) *MockIService_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_FindByCode_Call) Return(course1 *course.Course, err error) *MockIService_FindByCode_Call {
	_c.Call.Return(course1, err)
	return _c
}

func (_c *MockIService_FindByCode_Call) RunAndReturn(run func(ctx context.Context, courseCode string) (*course.Course, error)) *MockIService_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockIService
func (_mock *MockIService) FindByID(ctx context.Context, courseID string) (*course.Course, error) {
	ret := _mock.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *course.Course
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*course.Course, error)); ok {
		return returnFunc(ctx, courseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *course.Course); ok {
		r0 = returnFunc(ctx, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*course.Course)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, courseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIService_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
func (_e *MockIService_Expecter) FindByID(ctx interface{}, courseID interface{}) *MockIService_FindByID_Call {
	return &MockIService_FindByID_Call{Call: _e.mock.On("FindByID", ctx, courseID)}
}

func (_c *MockIService_FindByID_Call) Run(run func(ctx context.Context, courseID string)) *MockIService_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_FindByID_Call) Return(course1 *course.Course, err error) *MockIService_FindByID_Call {
	_c.Call.Return(course1, err)
	return _c
}

func (_c *MockIService_FindByID_Call) RunAndReturn(run func(ctx context.Context, courseID string) (*course.Course, error)) *MockIService_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseByCode provides a mock function for the type MockIService
func (_mock *MockIService) ReleaseByCode(ctx context.Context, courseCode string) error {
	ret := _mock.Called(ctx, courseCode)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseByCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, courseCode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIService_ReleaseByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseByCode'
type MockIService_ReleaseByCode_Call struct {
	*mock.Call
}

// ReleaseByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - courseCode string
func (_e *MockIService_Expecter) ReleaseByCode(ctx interface{}, courseCode interface{}) *MockIService_ReleaseByCode_Call {
	return &MockIService_ReleaseByCode_Call{Call: _e.mock.On("ReleaseByCode", ctx, courseCode)}
}

func (_c *MockIService_ReleaseByCode_Call) Run(run func(ctx context.Context, courseCode string)) *MockIService_ReleaseByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_ReleaseByCode_Call) Return(err error) *MockIService_ReleaseByCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIService_ReleaseByCode_Call) RunAndReturn(run func(ctx context.Context, courseCode string) error) *MockIService_ReleaseByCode_Call {
	_c.Call.Return(run)
	return _c
}

// ReserveByCode provides a mock function for the type MockIService
func (_mock *MockIService) ReserveByCode(ctx context.Context, courseCode string) error {
	ret := _mock.Called(ctx, courseCode)

	if len(ret) == 0 {
		panic("no return value specified for ReserveByCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, courseCode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIService_ReserveByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReserveByCode'
type MockIService_ReserveByCode_Call struct {
	*mock.Call
}

// ReserveByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - courseCode string
func (_e *MockIService_Expecter) ReserveByCode(ctx interface{}, courseCode interface{}) *MockIService_ReserveByCode_Call {
	return &MockIService_ReserveByCode_Call{Call: _e.mock.On("ReserveByCode", ctx, courseCode)}
}

func (_c *MockIService_ReserveByCode_Call) Run(run func(ctx context.Context, courseCode string)) *MockIService_ReserveByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_ReserveByCode_Call) Return(err error) *MockIService_ReserveByCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIService_ReserveByCode_Call) RunAndReturn(run func(ctx context.Context, courseCode string) error) *MockIService_ReserveByCode_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockIService
func (_mock *MockIService) Save(ctx context.Context, course1 *course.Course) (*course.Course, error) {
	ret := _mock.Called(ctx, course1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *course.Course
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *course.Course) (*course.Course, error)); ok {
		return returnFunc(ctx, course1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *course.Course) *course.Course); ok {
		r0 = returnFunc(ctx, course1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*course.Course)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *course.Course) error); ok {
		r1 = returnFunc(ctx, course1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockIService_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - course1 *course.Course
func (_e *MockIService_Expecter) Save(ctx interface{}, course1 interface{}) *MockIService_Save_Call {
	return &MockIService_Save_Call{Call: _e.mock.On("Save", ctx, course1)}
}

func (_c *MockIService_Save_Call) Run(run func(ctx context.Context, course1 *course.Course)) *MockIService_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *course.Course
		if args[1] != nil {
			arg1 = args[1].(*course.Course)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_Save_Call) Return(course11 *course.Course, err error) *MockIService_Save_Call {
	_c.Call.Return(course11, err)
	return _c
}

func (_c *MockIService_Save_Call) RunAndReturn(run func(ctx context.Context, course1 *course.Course) (*course.Course, error)) *MockIService_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIStore creates a new instance of MockIStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStore {
	mock := &MockIStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIStore is an autogenerated mock type for the IStore type
type MockIStore struct {
	mock.Mock
}

type MockIStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStore) EXPECT() *MockIStore_Expecter {
	return &MockIStore_Expecter{mock: &_m.Mock}
}

// DeleteByID provides a mock function for the type MockIStore
func (_mock *MockIStore) DeleteByID(ctx context.Context, courseID string) error {
	ret := _mock.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, courseID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIStore_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockIStore_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
func (_e *MockIStore_Expecter) DeleteByID(ctx interface{}, courseID interface{}) *MockIStore_DeleteByID_Call {
	return &MockIStore_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, courseID)}
}

func (_c *MockIStore_DeleteByID_Call) Run(run func(ctx context.Context, courseID string)) *MockIStore_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStore_DeleteByID_Call) Return(err error) *MockIStore_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIStore_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, courseID string) error) *MockIStore_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockIStore
func (_mock *MockIStore) FindAll(ctx context.Context) ([]course.Course, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []course.Course
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]course.Course, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []course.Course); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]course.Course)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStore_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockIStore_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIStore_Expecter) FindAll(ctx interface{}) *MockIStore_FindAll_Call {
	return &MockIStore_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockIStore_FindAll_Call) Run(run func(ctx context.Context)) *MockIStore_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIStore_FindAll_Call) Return(courses []course.Course, err error) *MockIStore_FindAll_Call {
	_c.Call.Return(courses, err)
	return _c
}

func (_c *MockIStore_FindAll_Call) RunAndReturn(run func(ctx context.Context) ([]course.Course, error)) *MockIStore_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCode provides a mock function for the type MockIStore
func (_mock *MockIStore) FindByCode(ctx context.Context, courseCode string) (*course.Course, error) {
	ret := _mock.Called(ctx, courseCode)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *course.Course
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*course.Course, error)); ok {
		return returnFunc(ctx, courseCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *course.Course); ok {
		r0 = returnFunc(ctx, courseCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*course.Course)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, courseCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStore_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type MockIStore_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - courseCode string
func (_e *MockIStore_Expecter) FindByCode(ctx interface{}, courseCode interface{}) *MockIStore_FindByCode_Call {
	return &MockIStore_FindByCode_Call{Call: _e.mock.On("FindByCode", ctx, courseCode)}
}

func (_c *MockIStore_FindByCode_Call) Run(run func(ctx context.Context, courseCode string)) *MockIStore_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStore_FindByCode_Call) Return(course1 *course.Course, err error) *MockIStore_FindByCode_Call {
	_c.Call.Return(course1, err)
	return _c
}

func (_c *MockIStore_FindByCode_Call) RunAndReturn(run func(ctx context.Context, courseCode string) (*course.Course, error)) *MockIStore_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockIStore
func (_mock *MockIStore) FindByID(ctx context.Context, courseID string) (*course.Course, error) {
	ret := _mock.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *course.Course
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*course.Course, error)); ok {
		return returnFunc(ctx, courseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *course.Course); ok {
		r0 = returnFunc(ctx, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*course.Course)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, courseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStore_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIStore_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
func (_e *MockIStore_Expecter) FindByID(ctx interface{}, courseID interface{}) *MockIStore_FindByID_Call {
	return &MockIStore_FindByID_Call{Call: _e.mock.On("FindByID", ctx, courseID)}
}

func (_c *MockIStore_FindByID_Call) Run(run func(ctx context.Context, courseID string)) *MockIStore_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStore_FindByID_Call) Return(course1 *course.Course, err error) *MockIStore_FindByID_Call {
	_c.Call.Return(course1, err)
	return _c
}

func (_c *MockIStore_FindByID_Call) RunAndReturn(run func(ctx context.Context, courseID string) (*course.Course, error)) *MockIStore_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockIStore
func (_mock *MockIStore) Save(ctx context.Context, course1 *course.Course) error {
	ret := _mock.Called(ctx, course1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *course.Course) error); ok {
		r0 = returnFunc(ctx, course1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockIStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - course1 *course.Course
func (_e *MockIStore_Expecter) Save(ctx interface{}, course1 interface{}) *MockIStore_Save_Call {
	return &MockIStore_Save_Call{Call: _e.mock.On("Save", ctx, course1)}
}

func (_c *MockIStore_Save_Call) Run(run func(ctx context.Context, course1 *course.Course)) *MockIStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *course.Course
		if args[1] != nil {
			arg1 = args[1].(*course.Course)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStore_Save_Call) Return(err error) *MockIStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIStore_Save_Call) RunAndReturn(run func(ctx context.Context, course1 *course.Course) error) *MockIStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
