basePath: /api/v1
definitions:
  course.Course:
    properties:
      code:
        type: string
      created_at:
        type: string
      end_date:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
      seat_available:
        type: integer
      start_date:
        type: string
      updated_at:
        type: string
    type: object
  course.CourseCodeRequest:
    properties:
      code:
        type: string
    type: object
host: localhost:8082
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: This is the Course Service API.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://example.com/terms/
  title: Course Service API
  version: "1.0"
paths:
  /courses:
    get:
      description: Retrieves all course data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/course.Course'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all courses
      tags:
      - Courses
  /courses/clean-dummy:
    delete:
      description: Delete all dummy course data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Remove all dummy courses
      tags:
      - Dummy
  /courses/find:
    get:
      description: Retrieves course data by code
      parameters:
      - description: Course Code
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/course.Course'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get course by Code
      tags:
      - Courses
  /courses/init-dummy:
    post:
      description: Create dummy data for testing
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/course.Course'
            type: array
      summary: Initialize dummy course data
      tags:
      - Dummy
  /courses/release:
    post:
      consumes:
      - application/json
      description: Release a seat for a course by specifying its course code
      parameters:
      - description: Course Code
        in: body
        name: course_code
        required: true
        schema:
          $ref: '#/definitions/course.CourseCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Release a seat for a course by course code
      tags:
      - Courses
  /courses/reserve:
    post:
      consumes:
      - application/json
      description: Reserve a seat for a course by specifying its course code
      parameters:
      - description: Course Code
        in: body
        name: course_code
        required: true
        schema:
          $ref: '#/definitions/course.CourseCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Reserve a seat for a course by course code
      tags:
      - Courses
swagger: "2.0"
