apiVersion: 1
groups:
    - orgId: 1
      name: course-app
      folder: course-app
      interval: 1m
      rules:
        - uid: ef26qjx5gcmbkc
          title: 'Course App: No Available Seats Error Count'
          condition: C
          data:
            - refId: B
              queryType: range
              relativeTimeRange:
                from: 3600
                to: 0
              datasourceUid: P8E80F9AEF21F6940
              model:
                datasource:
                    type: loki
                    uid: P8E80F9AEF21F6940
                direction: backward
                editorMode: code
                expr: count_over_time({app="course-app"} | json | level="error" | error="No available seats to reserve" [5m])
                instant: true
                intervalMs: 1000
                key: Q-982a6723-2d60-4804-9238-7f2f7470bd09-1
                legendFormat: 'request_id: {{request_id}}'
                maxDataPoints: 43200
                queryType: range
                range: false
                refId: B
                step: ""
            - refId: A
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - A
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: A
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                      unloadEvaluator:
                        params:
                            - 0
                        type: lt
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: adsm9gw
          panelId: 2
          noDataState: NoData
          execErrState: Error
          for: 1m
          keepFiringFor: 5m
          annotations:
            __dashboardUid__: adsm9gw
            __panelId__: "2"
            description: One or more 'No Available Seats' errors occurred in course-app in the last 5 minutes.
            summary: No Available Seats Error detected in course-app
          labels:
            app: course-app
            service: course-app
            severity: critical
            type: error
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
