services:
  postgres:
    image: postgres:17.2
    container_name: postgres
    platform: linux/amd64
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: P4ssword!
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    platform: linux/amd64
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dev
    restart: unless-stopped

networks:
  dev:

volumes:
  postgres_data:
  redis_data:
