services:
  mongodb:
    image: mongo:8.0.14
    container_name: mongodb
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: sandbox
      MONGO_INITDB_ROOT_PASSWORD: sandboxpass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - sandbox_net
  
  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    container_name: mongo-express
    restart: on-failure
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://sandbox:sandboxpass@mongodb:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: sandbox
      ME_CONFIG_BASICAUTH_PASSWORD: sandboxpass
    ports:
      - "8081:8081"
    networks:
      - sandbox_net
    depends_on:
      - mongodb
  
volumes:
  mongodb_data:

networks:
  sandbox_net:
    driver: bridge