[SERVICE]
    flush       1
    log_level   debug

[INPUT]
    Name  tail
    Path  /app/logs/member-app/app.log
    Tag   member-app

[OUTPUT]
    name        loki
    match       member-app
    host        loki
    port        3100
    labels      app=member-app
    label_map_path /fluent-bit/etc/map.json
    remove_keys container_id,container_name,source
    drop_single_key true
    line_format key_value

[INPUT]
    Name  tail
    Path  /app/logs/course-app/app.log
    Tag   course-app

[OUTPUT]
    name        loki
    match       course-app
    host        loki
    port        3100
    labels      app=course-app
    label_map_path /fluent-bit/etc/map.json
    remove_keys container_id,container_name,source
    drop_single_key true
    line_format key_value

[INPUT]
    Name  tail
    Path  /app/logs/booking-app/app.log
    Tag   booking-app

[OUTPUT]
    name        loki
    match       booking-app
    host        loki
    port        3100
    labels      app=booking-app
    label_map_path /fluent-bit/etc/map.json
    remove_keys container_id,container_name,source
    drop_single_key true
    line_format key_value